name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y clang pkg-config build-essential libssl-dev libudev-dev mold
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: indexer_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d indexer_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y clang pkg-config build-essential libssl-dev libudev-dev mold

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --version 0.8.6 --locked --no-default-features --features native-tls,postgres

      # - name: Run migrations
      #   env:
      #     DATABASE_URL: postgres://postgres:password@localhost:5432/indexer_db
      #   run: cargo sqlx migrate run

      - name: Check SQLx offline data
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/indexer_db
        run: cargo sqlx prepare --check -- --all-targets --all-features

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/indexer_db
        run: cargo test --workspace --all-targets --all-features --locked
